# Generated by Django 3.2.8 on 2021-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('assist_id', models.AutoField(primary_key=True, serialize=False)),
                ('Wedstrijd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Wedstrijd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wedstrijd',
            fields=[
                ('wedstrijd_id', models.AutoField(primary_key=True, serialize=False)),
                ('tegenstander', models.CharField(max_length=200)),
                ('datum_wedstrijd', models.DateField()),
                ('minuten_gespeeld', models.IntegerField(default=90)),
            ],
        ),
    ]
