# Generated by Django 3.2.8 on 2021-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_wedstrijd_soort_wedstrijd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedstrijd',
            name='tegenstander',
            field=models.CharField(max_length=200, verbose_name='Tegenstander'),
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='wedstrijd_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
