# Generated by Django 4.1.1 on 2022-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20211028_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedstrijd',
            name='seizoen_wedstrijd',
            field=models.CharField(default='21/22', max_length=200, verbose_name='seizoen'),
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='datum_wedstrijd',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='minuten_gespeeld',
            field=models.IntegerField(default=90, verbose_name='Minuten gespeeld'),
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='soort_wedstrijd',
            field=models.CharField(choices=[('Competitie', 'Competitie'), ('Beker', 'Beker'), ('Oefen', 'Oefen')], default='', max_length=300, verbose_name='Soort wedstrijd'),
        ),
    ]
