# Generated by Django 4.1.1 on 2022-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_wedstrijd_seizoen_wedstrijd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedstrijd',
            name='thuis_wedstrijd',
            field=models.BooleanField(default=True, verbose_name='Thuis wedstrijd?'),
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='seizoen_wedstrijd',
            field=models.CharField(default='21/22', max_length=200, verbose_name='Seizoen'),
        ),
    ]
